services:
  server:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/app/
    links:
      - php
    networks:
      - pg-network
  
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - pg-network
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      JWT_SECRET: linely-dev-jwt-secret-change-before-production
    volumes:
      - .:/app
    networks:
      - pg-network
  
  pgadmin-wdpai:
    image: dpage/pgadmin4:latest
    container_name: pg-admin3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
  
networks:
  pg-network:

volumes:
  pg-data:
