server {
    listen 80;
    server_name _;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name _;
    root /app/public;
    index index.php index.html;

    charset utf-8;
    ssl_certificate /etc/nginx/certs/linely.crt;
    ssl_certificate_key /etc/nginx/certs/linely.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
    }
}
